/* tslint:disable */
export const memory: WebAssembly.Memory;
export function create_sim(a: number, b: number): number;
export function update_sim(a: number, b: number): number;
export function set_panic(): void;
export function __wbg_actormove_free(a: number): void;
export function __wbg_get_actormove_actor_id(a: number): number;
export function __wbg_set_actormove_actor_id(a: number, b: number): void;
export function __wbg_get_actormove_direction(a: number): number;
export function __wbg_set_actormove_direction(a: number, b: number): void;
export function __wbg_actorid_free(a: number): void;
export function __wbg_get_actorid_actor_id(a: number): number;
export function __wbg_set_actorid_actor_id(a: number, b: number): void;
export function __wbg_js_simcommand_free(a: number): void;
export function __wbg_get_js_simcommand_actor_move(a: number): number;
export function __wbg_set_js_simcommand_actor_move(a: number, b: number): void;
export function __wbg_get_js_simcommand_actor_move_stop(a: number): number;
export function __wbg_set_js_simcommand_actor_move_stop(a: number, b: number): void;
export function __wbg_get_js_simcommand_actor_shoot(a: number): number;
export function __wbg_set_js_simcommand_actor_shoot(a: number, b: number): void;
export function __wbg_get_js_simcommand_actor_shoot_stop(a: number): number;
export function __wbg_set_js_simcommand_actor_shoot_stop(a: number, b: number): void;
export function __wbg_js_diff_free(a: number): void;
export function __wbg_get_js_diff_delete_entity_id(a: number, b: number): void;
export function __wbg_set_js_diff_delete_entity_id(a: number, b: number, c: number): void;
export function __wbg_get_js_diff_upsert_entity(a: number, b: number): void;
export function __wbg_set_js_diff_upsert_entity(a: number, b: number, c: number): void;
export function __wbg_get_js_diff_delete_process_id(a: number, b: number): void;
export function __wbg_set_js_diff_delete_process_id(a: number, b: number, c: number): void;
export function __wbg_get_js_diff_upsert_process(a: number, b: number): void;
export function __wbg_set_js_diff_upsert_process(a: number, b: number, c: number): void;
export function __wbg_get_js_diff_delete_player_id(a: number, b: number): void;
export function __wbg_set_js_diff_delete_player_id(a: number, b: number, c: number): void;
export function __wbg_get_js_diff_upsert_player(a: number, b: number): void;
export function __wbg_set_js_diff_upsert_player(a: number, b: number, c: number): void;
export function __wbg_siminterop_free(a: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function hash_test(a: number, b: number): number;
